# .github/workflows/publish.yml
name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Matches semver like v0.1.5

permissions:
  contents: read

jobs:
  publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build distributions
        run: |
          python -m build

      - name: Check built files
        run: |
          twine check dist/*

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
