name: Auto Tag

on:
  push:
    branches: [main]

jobs:
  tag:
    name: Auto Version Tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump patch version and create tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"

          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
            new_tag="v${major}.${minor}.$((patch + 1))"
          else
            new_tag="v0.1.0"
          fi

          echo "New tag: $new_tag"
          git tag "$new_tag"
          git push origin "$new_tag"
